### ISSUE TITLE
HIndent pragmas (file-header and declaration)

### ISSUE THREAD

**Issue by gibiansky** [chrisdone/hindent#109]
I am slowly working towards the goal of having `hindent` with the `gibiansky` style ready for serious use, which for me means being able to turn it on as a test on Travis and consider any formatting changes that `hindent` makes to be build errors. This would ensure that contributions follow the style of the rest of the project. (I am not sure this is a good idea, but I am curious to try it. It seems to work for `gofmt` and I want the Haskell community to have something similar.)

However, this is clearly infeasible *everywhere*. Some declarations should not be processed with `hindent`, and some files contain CPP, and so should not be processed either, as they cannot be parsed. To get around these problems, I propose adding a PRAGMA that `hindent` will respect, that will allow the user to turn `hindent` on or off for a particular declaration, file, or expression.

I propose it looks like this:
```haskell
{-# HINDENT on #-}
```
or
```haskell
{-# HINDENT off #-}
```
This can come before a module header, declaration, or expression; in each case it applies to the following item (except for the module header variant, in which case it applies to the entire file). 

How does this sound?

**Comment by chrisdone** [comment]
How might this interact with haddock documentation comments?

**Comment by gibiansky** [comment]
Good question. Since I want this to be usable for CPP files, the top-level pragma would literally prevent the entire file from being processed by `hindent`. 

So, let me make a more concrete proposal. I want two types of functionality:

1. Disable hindent for this entire file
2. Disable hindent for the following element (whether module, block, or expression)

I propose that in the latter case, any comments attached to it are disregarded and also not formatted. In the former case, `hindent` literally spits out what it was handed. 

The syntax for these two ideas is as yet unspecified, but probably via a single `HINDENT` pragma.

**Comment by chrisdone** [comment]
Right, I see two problems here:

1. Handling CPP. There're more options here.
2. Having hindent ignore code.

hlint actually runs the C-preprocessor on the code before parsing it. We can't do that, because we want to retain the `#` lines, but we could instead do limited processing. For example, something as trivial as:

``` haskell
x :: Int
#if __GLASGOW_HASKELL__ > 704
x = 706
#else
x = 704
#endif
```

Can easily be handled by formatting the individual blocks and then joining them back together with the original `#` macros. It would ignore the pragmas themselves entirely. Whereas inlining, like

``` haskell
x = 
#if __GLASGOW_HASKELL__ > 704
  706
#else
  704
#endif
```

is a bad habit anyway. Makes code harder to read, breaks a bunch of tooling (hindent, structured-haskell-mode, refactoring) and tooling yet to be invented. Changing inlining to top-level declarations is therefore a small price to pay for being able to nicely format the whole module. 

Maybe we can tackle two birds with one stone: With that in place, you could re-use the CPP process and have HINDENT made available as a boolean:

``` haskell
#if !HINDENT
x = code that hindent shouldn't touch
#endif
```

Granted, that's a little more heavy-weight than `{-# HINDENT off #-}`, although is less ambiguous and can work on many decls at once. I feel like inventing a pragma for code that HINDENT shouldn't touch is encouraging there to be code that hindent will never be able to format well. There's still the interaction with haddock: does Haddock support `DOC_COMMENT COMMENT DECL`?

Can you bring in some motivating examples?

**Comment by gibiansky** [comment]
My main motivating example is CPP -- I was under the impression that most tools simply "gave up" on CPP files, and that since `hindent` is thoroughly based upon `haskell-src-exts`, it was a somewhat hopeless endeavor to attempt to integrate CPP into the AST somehow. Using a pragma seemed fairly natural to disable CPP, and disabling it for a declaration seemed to be a good way to do it.

That said, if you have ideas on how to implement CPP without just ignoring it, it would be even better. I think it's perfectly fine to require non-inlined CPP. 

Would doing CPP in a better way require ditching `haskell-src-exts` for parsing, as it does not support CPP in its `parseModule`? If so, what could we do? I think we would want to avoid any upstream changes -- that seems like a very long release cycle and difficult to get right.

**Comment by chrisdone** [comment]
Suppose we do the dumbest solution possible:

1. Load the file in as one big string.
2. Split it up into chunks by lines that start with `#`.
3. Pay attention to `#if`, `#else` and `#endif` but only ones that are `#if HINDENT` or `#if !HINDENT` in which case we don't format the following chunk.
4. Otherwise format any other chunk.

Spit out the file with the `#` lines verbatim and the other chunks. How does that sound?

I don't see an occasion where any other variable or condition (e.g. `__GLASGOW_HASKELL__`) would affect whether we want hindent to format that code or not. For 99.9% of CPP we shouldn't even be looking at the macros I think, just pretty printing the Haskell chunks between them.

**Comment by gibiansky** [comment]
This sounds fairly reasonable. I'll take a shot at implementing it eventually.

**Comment by gibiansky** [comment]
Implemented it on PR #110; if it looks good and you are satisfied with this simple approach, let me know and I'll rebase and merge it.

**Comment by chrisdone** [comment]
Merged #110, nice work.

**Comment by gibiansky** [comment]
I'm satisfied with what we have now so closing this issue; that said some of the ideas here might still be relevant, so if you or someone else is interested in continuing the discussion you should reopen this issue.

**Comment by michalrus** [comment]
Related: https://github.com/commercialhaskell/hindent/issues/442
