### ISSUE TITLE
Aligning inline comments

### ISSUE THREAD

**Issue by pharpend** [chrisdone/hindent#119]
Hey, @gibiansky . Could you configure your style such that inline comments are aligned?
Something like this:

```haskell
openEditor :: String        -- ^Name of the editor.
           -> String        -- ^Template for the file name. See 'openTempFile' from "System.IO.Temp".
           -> ByteString    -- ^Initial contents of the file
           -> IO ByteString -- ^Resulting ByteString
```

**Comment by gibiansky** [comment]
@pharpend This existed in an earlier version of the style, but I found it quite brittle. In addition, it sometimes aligned comments I did not want aligned, for example:

```haskell
-- | Do a thing!
thing :: A    -- ^ Param 1
      -> B    -- ^ Output
thing = undefined
```

would be reformatted to


```haskell
              -- | Do a thing!
thing :: A    -- ^ Param 1
      -> B    -- ^ Output
thing = undefined
```
which is clearly wrong. 

Now, you could detect such scenarios, but it turns out they occur rather often...

You could probably specialize aligning just for arguments to functions and record fields, though. I think I would be willing to use that. As it is I'm actually not entirely happy with comment handling -- especially comments in record fields sometimes don't work properly.
