### ISSUE TITLE
Gibiansky style ignoring line length

### ISSUE THREAD

**Issue by pharpend** [chrisdone/hindent#121]
Perhaps it could read `fill-column`, and guess from that.

**Comment by geraldus** [comment]
Can you recheck? I have `fill-column` set to `80` and when I use `M-q` to reformat code it always takes care about it, making lines to fit 80 characters wide.

**Comment by pharpend** [comment]
@geraldus I think it's a bug in the @gibiansky style, actually. What style are you using?

**Comment by geraldus** [comment]
Chris' one.

**Comment by pharpend** [comment]
I'm away from Emacs right now, but I'll give some examples later.

**Comment by pharpend** [comment]
Alright, my `fill-column` is `70`. I use `M-x hindent/reformat-decl` to reformat my code (or rather, a key bound to `M-x hindent/reformat-decl`. Here is a function of mine, as formatted by the @gibiansky style:

```haskell
-- |Get the project from the user
getProject :: IO Project
getProject = getProjectBS >>= \pbs -> case decodeEither pbs of
               Left err -> fail err
               Right (NewProject nom mtrs hp descr) -> do
                 newNom <- if | nom == _repl_working_dir -> T.pack . last . split "/" <$> getCurrentDirectory
                              | otherwise -> pure nom
                 pure $ Project newNom (mtnrToPerson <$> mtrs) hp descr []
```

The longest line there is `105` chars long, far beyond the limits of my `fill-column`.

@chrisdone's style formats this to 

```haskell
-- |Get the project from the user
getProject :: IO Project
getProject =
  getProjectBS >>=
  \pbs ->
    case decodeEither pbs of
      Left err -> fail err
      Right (NewProject nom mtrs hp descr) ->
        do newNom <-
             if |  nom == _repl_working_dir ->
                  T.pack .
                  last .
                  split "/" <$>
                  getCurrentDirectory
                |  otherwise -> pure nom
           pure $
             Project newNom (mtnrToPerson <$> mtrs) hp descr []
```

The longest line there is 62 characters, well below the limit.

**Comment by pharpend** [comment]
I changed the title, because this is apparently a problem with @gibiansky's style.

**Comment by gibiansky** [comment]
@pharpend I'm not sure this is a problem IMO.

I am generally not a big fan of `hindent` rearranging infix operators for me, specifically trying to decide whether or not there should be newlines before or after them. Infix operators are very flexible in Haskell, and there are a lot of ways to lay them. In general, I prefer that the `gibiansky` style generates readable and good looking code, and if that isn't possible with a 100-line limit, that's the fault of the original code, not of `hindent`. 

Specifically, in this case, I would just add a newline after the first `=`.

That said, I'm open to suggestions for specialty formatters for infix operators. In this case, you could argue that `a . b . c . d` could always be reformatted to `a .`, `b .`, `c .`, etc, followed by newlines.

**Comment by pharpend** [comment]
@gibiansky The problem is that there's an argument for line length, and your style is ignoring it. Whether or not you agree with the argument is irrelevant.

**Comment by gibiansky** [comment]
@pharpend Apologies for the fairly length response. I would like to make clear a few things about how and why the `gibiansky` style functions as it does, and make it clear what sort of changes I agree with and don't agree with. I discuss specifics of line length handling options at the end.

First of all, `hindent` does not have strict standards for what a "compliant style" is, so a style is perfectly within its rights to completely ignore the line length flag. In fact, all the styles do that in some cases, such as the following input:
```haskell
longveryLongveryLongveryLongveryLongveryLongveryLongveryLongveryLongveryLongveryLongveryLong = hello + 1
```
With `--line-length 100`, this is possible to format properly, yet *none* of the styles currently available do that. `hindent` does not (as of yet) have a policy for what a "proper" style is, so there is no issue with styles that ignore things such as line length arguments. Though I do not believe this applies to any current style authors, it is perfectly within the realm of an author's rights to declare that 100 (or 80, or any other number) is the proper line length, and that their style will support *nothing* else, because that is what they believe Haskell code should be formatted as. If we want to change this and have an official policy regarding proper styles are, this is a separate discussion entirely, and should be rigorously enforced with a test suite.

With that said, I think that there is a range of acceptable line lengths, and that the line length flag should be well supported. In fact you can see that I have in the past [pushed for the existence of this flag](https://github.com/chrisdone/hindent/issues/69), because I find it very useful.

However, it is *impossible* to *always* reformat code to fit within a given width, and even more impossible to do so while maintaining what I consider good coding style. I can have arbitrarily long identifiers which make it hard to do so, of course. I can try to fit as much code as I want into a line. 

Our styles differ in what they consider acceptable formatting. For example, consider the code
```haskell
abc = (this + is + a + very + long + string + off) .  words + this + is + a + very + long + string
```
The `chris-done` style reformats this to
```haskell
abc = 
  (this + is + a + very + long + string + off) .
  words +
  this +
  is +
  a +
  very +
  long +
  string
```
which I consider to be very unidiomatic and hard to read. I would have reformatted this manually to something like
```haskell
abc = 
  (this + is + a + very + long + string + off) .  words
  + this + is + a + very + long + string
```
Note that the operators here are just made up; clearly the code here doesn't actually make sense, it's just for demo purposes.

Now, you may argue that compliance with line length is more important than (what I consider to be) readable code. I would disagree.

The `gibiansky` style reflects my opinion about Haskell formatting and the role of `hindent`. Namely:

1. The look and feel of all code run through `hindent` with a particular style should be the same.
2. `hindent` is not a fix-all: there are places where you need to adjust things yourself.
3. In places where there is not a clear way of doing things, and I do not believe there should be one and only one way of doing something, `hindent` should respect the user's preferences (in that it does not modify the code in those places). This is reflected in the fact that the `gibiansky` style tries fairly hard to preserve whitespace in relevant places, such as between declarations and before comments.

A consequence of points 2 and 3 is that in some places `hindent` with my style may not make decisions that you want it to make for you, and instead force those decisions to be made by the user. The formatting of infix operators is one such place. Infix operators are so varied in their usage and meaning that I do not think it makes sense to have a single style for all of them; this is why `gibiansky` style hardcodes `$` and the applicative operators. 

Now, onto line length. Line length is handled by searching through the space of possible formats; there are many places where `hindent` can make a decision to break or not break a line, and it by default tries to do a single line, and if it can't, resorts to multiple line formatting. Infix operators are *not* one of the places it gets to make a decision in `gibiansky` style, because I do not think the resulting layout consistently reflects what I would do if I were manually observing my own style guidelines. As such, in the case of infix operators, I prefer to fix the original code, so that `hindent` can do things with it.

In this specific case, I see a few options for how line length can be decreased:

### Option 1
 Hardcode the `.` operator to allow for column style usage (when there are at least 2 uses of the operator):
```haskell
a = f .
    g .
    h
```

Note that I think that is a common style for `.`, but not for other operators, so I do not think this should be an option for *all* operators. Also note that I think this should require multiple uses of the operator.

### Option 2 (maybe)
Allow column style for *any* operator, as long as its always the same operator, and there are at least 2 of them:
```haskell
a = c +
    d + 
    e
```

### Option 3
Insert line breaks after declarations *if* there is a line length issue. Otherwise respect the user's choice. (By declaration I mean the top level declaration, e.g. add a newline after the `=`)

### Option 4
Do the same as option 3, except for `case` and multiway `if`s.

I consider all of these options *probably* an improvement. However, note that none of them handle the line length question in general, because I do not think that code cleanliness should be sacrificed for line length by an automated tool. That is a decision for the user to make; also, I often use line length as an indicator that I should break my code down into simpler named subexpressions, and think that this practice makes my code cleaner and easier to read.

I am happy to implement something along the lines of options 1 through 4, and come up with similar options (if it is necessary) for other places where the `gibiansky` style generates long lines. I do not know when I will be able to do this, hopefully soon; For the moment being I am a full-time student and cannot allocate nearly as much time as I would wish to hindent or IHaskell, my other project.

That said, I am more than happy to accept code contributions to the `gibiansky` style that implement the above options (as well as other contributions that maintain the overall style I am going for and have tried to describe above). Finally, if you disagree with choices I've made in the `gibiansky` style, it's fairly straightforward to copy the `gibiansky` style code and make the changes you wish to create another style that differs from mine, though of course I would prefer compromise and code contributions over style forks.

**Comment by geraldus** [comment]
As for me, I've found that `hindent` does not gives me expected profit; there is a lot of cases where manual code format will give much readable and nice code, which automated formatting program will never give, obviously, it should be very smart in this case, hence very complicated.
When I use auto reformat I have to rearrange or realign things manually often, spending time, while I'm expecting that auto-format should save my time. Thus, for now I've back to manual formatting now. Although, I think it is good to see different code styles and mix them according to your needs.

**Comment by gibiansky** [comment]
@geraldus That seems somewhat counterintuitive. It seems like `hindent` should save *some* time off the formatting, if not all of it; particularly complex cases will require manual formatting, but in many cases `hindent` should be sufficient. (That said, I have a similar experience. That is why my style tries to respect user formatting in many places -- so that `hindent` plus manual formatting is viable.)

As an aside, `hindent` can also be used to force a somewhat consistent style across all contributors to a project, which I find useful.

**Comment by geraldus** [comment]
@gibiansky I agree, when you have many contributors, auto formatting really shines.
The reason why I switched to Chris Done's style, because I don't like long whitespace gaps (as shown in @pharpend [comment](https://github.com/chrisdone/hindent/issues/121#issuecomment-93895252)).
Can I control it somehow?

**Comment by gibiansky** [comment]
Control the whitespace to the left? In this case, I think no.

(The reason for that is that the `case` is an expression in a lambda, and infix expressions do not go to the left of their first argument. That way you never end up with something like this:
```haskell
aLongFunctionName with some arguments = a very long expression + (case x of
  Nothing -> 0
  Just x -> 100)
                                        + 3
```
but will instead have
```haskell
aLongFunctionName with some arguments = a very long expression + (case x of
                                          Nothing -> 0
                                          Just x -> 100)
                                        + 3
```
which is IMO easier to read.

So I guess the short answer is: reduce the whitespace by moving your code to eliminate that whitespace, rather than relying on hindent. I would have written that as
```haskell
-- |Get the project from the user
getProject :: IO Project
getProject = do
  pbs <- getProjectBS
  case decodeEither pbs of
    Left err -> fail err
    Right (NewProject nom mtrs hp descr) -> do
      newNom <- if | nom == _repl_working_dir -> T.pack . last . split "/" <$> getCurrentDirectory
                   | otherwise -> pure nom
      pure $ Project newNom (mtnrToPerson <$> mtrs) hp descr []
```
or as
```haskell
getProject :: IO Project
getProject =
  getProjectBS >>= \pbs -> case decodeEither pbs of
    Left err -> fail err
    Right (NewProject nom mtrs hp descr) -> do
      newNom <- if | nom == _repl_working_dir -> T.pack . last . split "/" <$> getCurrentDirectory
                   | otherwise -> pure nom
      pure $ Project newNom (mtnrToPerson <$> mtrs) hp descr []
```
Ultimately my style will not work everyone, as it *does* require having somewhat appropriate coding habits.)

**Comment by geraldus** [comment]
In case of `aLongFunctionName` I'd prefer to use `where` or `let` to move `case` expression out. Your last two code examples looks perfect to me.

**Comment by chrisdone** [comment]
I'd echo @gibiansky's explanation about style and their adherence to arguments. The line length is just intended as a guide that styles can ignore, use as a suggestion, or try to make as a hard limit but at the end of the day I feel it's preferable to have styles cheap to make and opinionated than laden with options and democratic.

I understand the motivations for @gibiansky's examples e.g. the `abc` one; it yields nice results but comes with an understandable implementation complexity with a lot of judgment calls. There're examples in the `chris-done` style where it exceeds the limit; I have a few in my codebases but at some point I consider it time to refac my code. Also my style doesn't do anything clever with operators: if they fit on one line and are non-"complex", so be it, otherwise it indiscriminantly puts them all on separate lines, which is probably what yields the advantagous 62 characters in @pharpend's example.

As a general personal policy, my style does the dumbest most predictable thing possible. It basically formats code like Lisp. If there were aesthetic alignments or embellishments I would make in the past, I've discarded them in favor of the more general style as it starts to matter less when the gain is: hey, I don't have to manually do *anything* and simpler formatting rules mean I pretty much always know what's going to happen. YMMV. @gibiansky's is the most complex style implementation so far so there're more points open to debate, I expect.

**Comment by gibiansky** [comment]
I think it's particularly important to emphasize:

> As a general personal policy, my style does the dumbest most predictable thing possible. It basically formats code like Lisp. If there were aesthetic alignments or embellishments I would make in the past, I've discarded them in favor of the more general style as it starts to matter less when the gain is: hey, I don't have to manually do anything and simpler formatting rules mean I pretty much always know what's going to happen.

Specifically, @chrisdone's style and my style take diametrically opposite approaches: the `chris-done` style aims to be universal and does not care whether it looks like what most people consider typical Haskell code, whereas `gibiansky` style tries very hard to look like standard Haskell code you would see in the wild or on Reddit at the expense of being universal. 

Note that I've opened https://github.com/chrisdone/hindent/issues/126 for further discussion of concrete improvements to the way `gibiansky` style handles this.

**Comment by chrisdone** [comment]
+1

**Comment by gibiansky** [comment]
I've started working on this in https://github.com/chrisdone/hindent/commit/d64f47adac933b8d7a7c5d834840a29e3751fdac

It turns out it's actually trickier than I expected. 

Since the style makes decisions *as* its printing output, it can't make decisions based on things it hasn't printed. For example, when it formats something like `a + b`, it starts by printing `a`, then `+`, then `b`. But, if there are two ways to print whatever `a` is (a single line and multi line version), then it will choose the shorter single line one, because it doesn't yet know how long `+ b` will be, and so may not realize that choosing a single line `a` results in a multi-line `b`. If `a` can be single-lined but `b` can't, the result is that it does nothing.

I've encountered similar issues a number of times. The ultimate issue is that it needs to be able to do a *real* backtracking search through the space of formats, and *not* be writing as it goes. Sadly this requires a very different architecture from what we have.
