### ISSUE TITLE
Vim: invalid, all-in-one-line output

### ISSUE THREAD

**Issue by elvis-sik** [chrisdone/hindent#150]
I have added the vim plugin to .vim/autoload
I have this code

 > main = do
 >  foo <- putStrLn "hello world"
 >  print foo
 >

I select it using visual mode (doesn't matter if it is up to the line following print or up to that line) and press `gq`. The output I get is:

 > main = do foo <- putStrLn "hello world" print foo

If I call hindent in the command line, it outputs correctly.

Any ideas?

**Comment by chrisdone** [comment]
vim probably removes the newlines.

**Comment by elvis-sik** [comment]
I think so. Do you know anyone who may know how to fix this? I tried reading the docs but wasn't able to find anything.

**Comment by chrisdone** [comment]
Don't know anything about vim, sorry. Maybe @gibiansky knows.

**Comment by gibiansky** [comment]
@elvis-sik I think the most likely reason it's not formatting is that it's using `vim`'s default `gq`, not `hindent`. 

Try including it directly using `source hindent.vim` rather than putting it in `.vim/autoload`. Then open an `*.hs` file (or create one) and try using `gq` (it won't use the Haskell `gq` unless it knows it's a Haskell file, so just opening a blank file and writing some code in it without saving won't work).

I generally bind `<Leader>r` or something like that to a combination of `hindent` and [vim-textobj-haskell](https://github.com/gibiansky/vim-textobj-haskell) so that I can just press `<Leader>r` and have it reformat whatever declaration my cursor is currently on. Makes it rather thoughtless to keep things nicely formatted.

**Comment by elvis-sik** [comment]
Thanks, this tip uncovered the problem! I littered the `FormatHaskell` function with `echo`, and even changed the command to `hindent ABCD`, and found out it wasn't been called at all. I trimmed some lines of the code and added it to my `vimrc` and it is working. What is a little strange for me is that it doesn't work if I place in `ftplugin/haskell.vim`. Nevertheless, thank you! Now I gotta choose a style :)
