### ISSUE TITLE
Invalid rendering of explicit forall in class instances

### ISSUE THREAD

**Issue by sheyll** [chrisdone/hindent#218]
Hello there,

Hindent is really important tool to me, I use it on a day-to-day basis, so thank you!

I can contribute awareness of small issue with the `cramer` formatter (Version 4.6.4).

[online-example](http://chrisdone.com/hindent/?s=instance%20forall%20x%20.%20C)

    instance forall x . C

is rendendered as

    instance xC

which is clearly invalid syntax, and probably causes compile errors.

I have looked at the code in 4.6.4 as well as the master branch, I could not figure out whats going wrong there.

If I were to take a shot at it, in what branch do you recommend doing it? Is it planned to have bug-fixes in 4.6.4 or is all new development focussed on 5.x?

wbr Sven

**Comment by chrisdone** [comment]
This occurs in hindent 5 so I'll mark this as a bug and fix it, thanks!

> If I were to take a shot at it, in what branch do you recommend doing it? Is it planned to have bug-fixes in 4.6.4 or is all new development focussed on 5.x?

I'd recommend using hindent 5 because that's where dev and improvements are going on in a (hopefully) general community direction. 😉 ☝️ 

But if you're married to the Cramer style, @gibiansky has said that he's maintaining hindent 4 here: https://github.com/gibiansky/hindent So I think you can contribute fixes there and use that version. 😄 👍
