### ISSUE TITLE
Module merge functionality

### ISSUE THREAD

**Issue by tonyday567** [chrisdone/hindent#74]
A major time-suck in my workflow is cut/pasting code.  Refactoring some functions to a new module involves:
- cut functions
- paste into new file
- move to top of old file, think about and cut necessary imports, pragmas & export lists
- merge these into the right spots in the new file.

I'd like to have a stab at some emacs functionality to help with this, and I think hindent, or at least HSE, is the right tool:
- haskell-copy, which would copy the pragmas, imports etc at the same time as the normal copy.  What was copied/cut would be a `Module NodeInfo`
- haskell-merge, which would paste the cut text, and merge the imports etc to the new file, via something of the form `Module a -> Module a -> Module a`.
You would be left with some extraneous pragmas and imports in the new file, but this is fairly easy to deal with.

Would this sort of thing fit in with hindent, or would it be better off elsewhere?

**Comment by gibiansky** [comment]
I suspect this is not quite `hindent` material. However, I would suggest either a) a tool that does this based on the `hindent` library or b) integrating this perhaps into HaRe? `hindent` does expose a lot of its internals via the library, and could hypothetically expose more, perhaps?

I don't know much about HaRe but it's meant for refactoring, which this fits better with.

**Comment by tonyday567** [comment]
HaRe is big and scary - refactor with a capital R.  I was looking at simple tools to save a few key-strokes and brain-cycles.  It seems like @alanz is concentrating on the GHC API for the moment as well - alanz/HaRe#17.

Meanwhile, flycheck/hindent/shm is really working very well for me.  My guess is that smaller concerns such as hindent will be better able to quickly utilise the GHC API when it's finished.

But I take your point on the idea being somewhat outside of hindent's mission.

**Comment by tonyday567** [comment]
I'd also add [stylish-haskell](https://github.com/jaspervdj/stylish-haskell) into the mix.  hindent hasn't done much in the way of formatting pragmas and imports, and has concentrated on formatting chunks.  stylish haskell does pragma and import formatting, and some, (but not much), declaration formatting (which tends to be opinionated). Both are haskell pretty printers using HSE.

**Comment by chrisdone** [comment]
Echoing what @gibiansky said. A secondary motivation for hindent is that if a user or user(s) are comfortable with a tool reformatting their code and that their codebase is already formatted with that tool, this makes implementing refactoring tools substantially easier because the tools don't have to waste time figuring out how to reproduce the user's style.

> HaRe is big and scary

I share your sentiment. I'm a supporter of refactoring tooling and HaRe is an old project which hasn't delivered much of interest for me personally. It seems like a lot of work for a few special cases which could be handled with generally better editor support. 

>  hindent hasn't done much in the way of formatting pragmas and imports, and has concentrated on formatting chunks.  

The reason for this is that:

* hindent is not perfect.
* Sometimes—rarely, but it happens (typically on other styles)—hindent formats in a way that I don't like. So I don't use it on one declaration.
* When I'm working on someone else's codebase, the ability to only reformat the declaration that I'm writing myself, and not the whole module, is very important.

The problem with tools like stylish-haskell is that they touch the whole module and I don't trust it enough to do that. I don't trust hindent to do it either. Characters like `^K` that one uses in Emacs are stripped away by HSE, as is unicode in string literals, hex literal numbers are rewritten to decimals, etc. So while I use hindent constantly to reformat the declaration I'm writing, I use it selectively. And that's why reformatting whole modules has been an effort almost exclusively driven by other people.

**Comment by gibiansky** [comment]
With all that said, though, I think your task is the sort of thing that you could write custom tool for using `hindent` as a library. That has the best of both worlds – you get to use `hindent`, which is pretty close to what you want, yet the code doesn't have to live in `hindent`, which has a somewhat different goal.

@chrisdone For the reasons that you've described, I've been working on allowing more user-controlled behaviour in my style (especially newlines). Since `hindent` isn't perfect, I rarely want to run it on whole modules, but perhaps if it respected some portion of my original style, it would work that way well. Of course that comes with trade-offs, but I think that using `hindent` on whole modules is definitely possible and will work well with a little bit more work. I'm still unsatisfied with my style so don't use it in production as often as I'd like to, though, so we'll see how the further advancement goes.

**Comment by tonyday567** [comment]
> Characters like ^K that one uses in Emacs are stripped away by HSE, as is unicode in string 
> literals, hex literal numbers are rewritten to decimals, etc.
Ok, I didn't know that.  That's bad - I was thinking the first order of business for a refactoring tool would be a clean round-trip that left the code unchanged.
