### ISSUE TITLE
Support --refactor flag 

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/hindent#75]
Opening as a separate ticket to track any further discussion. As `configRefactor :: Bool`. This'll allow a style to make static transformations to the AST which styles normally shouldn't do (as it can be annoying to have things removed when you're in the middle of something). Copy the transformations from the `TonyDay` module and put them in e.g. `HIndent.Refactor` or something. Styles can import this for now. 

I don't have a story for handling when a style wants to refactor something differently to the default, so for now it's easier if styles "opt-in" than get it by default and struggle to workaround it.

Pinging @gibiansky @tonyday567

**Comment by gibiansky** [comment]
I'm a bit iffy on this flag, personally. I think that totally minor things like mentioned by @tonyday567 can be done automatically (if a style chooses to) and don't need to be behind a flag, and for larger refactors this is not fine grained enough. Not sure, though.

I do like the idea of this behaviour being configurable. For instance, I am a big fan of `hlint` suggestions, and may consider making this flag automatically implement them for the `gibiansky` style. (How do you feel about an `hlint` library dependency? Is that too onerous or ok?)

**Comment by chrisdone** [comment]
Hmm, thinking about this more I'm having more conservative feelings.

The problem I have with doing refactorings automatically is that I can imagine being in the middle of writing something, writing some code with redundancy in it because I'm part way through, hitting reformat (which I do regularly) to get a cleaner view and then discovering to my umbrage that it has removed what I just wrote. Leaving me with the choice of "badly formatted code or we remove something you just wrote."

In your hlint example you might be writing `(\x -> f x)` and hit reformat and then hlint will replace it with `f` and now you have to create the lambda again to continue writing `(\x -> f x <|> p)` or whatever.

hlint as a dependency seems okay. 

But stepping back, perhaps we're putting too much into hindent which currently has a relatively straight-forward purpose of pretty printing (clue is in the name hindent). This feels like we're entering feature creep territory.

In the interest of caution, I'm going to move this recent AST-rewriting stuff to another branch while we mull this over. In my original vision of hindent I had explicitly precluded rewriting of the AST, and, incidentally, of preserving user formatting. Let's regroup and maybe give @ndmitchell and others time to weigh in.

**Comment by chrisdone** [comment]
904beb5 reverts @tonyday567's rewriting and also the `--refactor` flag, but the [refactoring](https://github.com/chrisdone/hindent/tree/refactoring) branch has that code.

**Comment by ndmitchell** [comment]
So I am completely happy with you using HLint in HIndent (just in case there was ever any ambiguity to that). I'd really like HLint to have an "automatically replace" flag, but I want to do it preserving whitespace and style, which is quite hard. You'd ideally like to have both hlint and hindent available separately and then have people just use the composition on their end, but it's much easier to write the composition, so I can see why that's desirable. Given the current code structures, if we were going to put the composition in either half, it seems hindent is a better place since you can do the replacement with or without hlint. I appreciate it's not a transform you'd want to apply all the time, and would want to be an option, but it seems like it would suit some people.

So I'd be very happy to see this in hindent. Alternatively, perhaps someone should write the hlindtent package which just uses the two API's together to get the composition, although that may mean duplicating some of the bits of hindent (not sure how much).

**Comment by tonyday567** [comment]
> But stepping back, perhaps we're putting too much into hindent which currently has a relatively 
> straight-forward purpose of pretty printing (clue is in the name hindent). This feels like we're 
> entering feature creep territory.

In my mind, I divide the problem domain into:  
An element of refactoring that is about pretty printing - regularising spaces between chunks, fixing up badly formatted pragmas etc. Definitely hindent.

Cleaning up the code, but leaving the sematics unchanged - ordering declarations according to the export list, sorting imports and removing duplicates, removing commented-out imports etc.  I see this layer as about using HSE to recognize features of a module that aren't captured by GHC.  It could be done withing emacs say, but would be extremely difficult.  HSE is the right tool for the job.
Finally there's changing code using hlint and ghc. I'm also a big fan of hlint and accept 90% of the recommendations (I turn them off if I don't), and am interested in automation of this.  But there is choice here - for example, to go via flycheck and thus fit in with the overall emacs ecosystem.
Inclusion of hlint then moves away from the idea of hindent as a HSE front-end (but towards a better style formatter).

**Comment by tonyday567** [comment]
What I was definitely looking for in the tonyDay style was an ability to compose some whole-module refactors with the lower-level styles, and Neil's ideas on hlint are in tune with that.  In an ideal world you'd go with hlindent as a separate effort (and I'd throw in ghc warnings refactors like inclusion of type sigs and other such stuff).
But I've just finished having a close look at the haskell-emacs toolchain and my guess would be that the conceptual space is full up.  There's a good chance yet another project would wither no matter the quality.

**Comment by ndmitchell** [comment]
I guess having three levels of tools makes sense:

* hindent, which works on the lexical structure.
* hlint, which works on the syntactic structure.
* something derived from the GHC API, which works on the semantic structure.

As such the whole-module refactors likely belong in hlint. The only stumbling block is that HLint doesn't apply replacements.

**Comment by tonyday567** [comment]
I've noodled around with hindent, and taken a quick look at hlint, and there's a few items I'd like to get feedback on.

File versus Text
---
There's some impedance between the API of hindent (based on text), the idea of whole module operations and the hlint ide (which pretty much requires file-level given cross-module linting). Could/should we include an option to feed a file in hindent? 
At the same time, I'm currently using regex in emacs to match and replace hlint suggestions, so a hlint text checker is a vast improvement on current tools, and I'm keen to try it out in a hindent setting.

Before | After
---
My head hurts after going through the annotateComments logic, but it seems that comments are being attached to the wrong nodes.  I think a major culprit is in the [insert](https://github.com/chrisdone/hindent/blob/master/src/HIndent.hs#L187).  Nodes can have the same srcSpan so equality of node based on that is stuffing up.
Placing a comment and moving them to different nodes correctly is essential for syntax changes eg changing `putStrLn {- inside -} . show {- end of line -}` to `print {- end of line}`.
I'd like to have a stab at refactoring the placement helpers starting with something like:

    data Direction = Before | After
    data Attachment = HighestLayer | LowestLayer deriving (Eq)
    data Location = Before' | After' | Inside | Wrapping | Overlapping | Same deriving (Eq)

The attachment idea is that typically there are many nodes that are equally `close` to a comment and a decision needs to be made about which level of node to associate the comment with.
I think this type of AST helper will also be quite useful to style-only manipulations (eg knowing that a node is inside a larger particular node might change the style decision).

But this is a rabbit hole that others might have fallen through before, so any ideas appreciated before I take the plunge.

HLint and refactoring branch
---
Is it ok to add a hlint dependency to the refactoring branch and otherwise make more sweeping changes?  Or are there any second-thoughts about doing this work in hindent?

**Comment by tonyday567** [comment]
@ndmitchell comment
If hlint goes for replacement functionality, anything across multiple lines is going to want some prettyPrinting (unless there's some exactPrint functionality out there I don't know about), and hindent is probably the right prettyPrinter, so that will lead to a hindent dependency.  Your split looks right to me, but syntactic changes create lexical ones (and sematic changes create lexical and syntactic ones!).

**Comment by alanz** [comment]
From GHC 7.10 RC2 you will be able to make changes to the AST and then output them preserving original formatting, but there are still some libraries that need to firm up for this.

The basic infrastructure I envisage is

GHC API
ghc-exactprint
some to-be-written library providing manipulation combinators.

The new library would have to make code like https://github.com/alanz/HaRe/blob/ghc-7.10/src/Language/Haskell/Refact/Refactoring/Case.hs#L69 more straightforward.

**Comment by tonyday567** [comment]
Hi @alanz,
I only vaguely follow the code linked, but I think I get the spirit of it.  Refactored code causes changes in srcSpan that needs to be propagated to trailing code srcSpan's.  Is that the zone for the new library?

**Comment by alanz** [comment]
ghc-exactprint is a two-pass process, the first generates annotations from each SrcSpan giving relative placement of items, indexed by original SrcSpan. The second generates output by passing over the AST, looking up the annotations based on the SrcSpan, and using the relative locations to ensure original spacing is preserved.

The new library would be to have a set of simple operators to take the origainal AST and relative annotations, and make changes to it, introducing new unique SrcSpans and relative annotations as required.

This will allow indentation/dedent, or moving sub-elements around, e.g. converting an if statement to a case statement, or moving a declaration from a where clause to the top level or vice versa.

**Comment by tonyday567** [comment]
I chipped away at this for a while, but it's found it's way to the too-hard basket.  The HIndent.Refactoring module is where I've gotten to with testing.

I refactored HIndent.Comments to get some finer-grain control, and got some reasonable results (with correct comment placement) from an HIndent.Styles.Exact style.  placeComments is the candidate replacement for annotateComments.

After this refactor, however, I found comments could only be placed/annotated in certain positions in the ast.  testVar' in HIndent.Refactoring documents the problem.

Personally, my conclusion is that coding up safe refactorings (with a non-infinite time budget) will require a tighter set of tools than is currently available.  exactPrint in haskell-src-ext lacks some flexibility about comment placement, hlint provides String-based refactoring suggestions rather than ast-based ones, and hindent is engineered above an abstraction level that allows for rigour in round-tripping.

What is necessary (and would be awesome) is an AST Prism, similar to https://hackage.haskell.org/package/JsonGrammar-1.0/docs/Language-JsonGrammar.html and other recent chatter.
